### PR TITLE
Implement 3x3 Inventory access for Pattern mode

### PR DESCRIPTION
**Pull request by aria1th**
also moves some code parts to fabric transfer API.

Detail : Dropper will think 3x3 Area behind it as 'storages', and takes item from them.

### CODE REVIEW

**Comment by FakeDomi** [comment]
I'm wondering, what's the use case for this?

**Comment by aria1th** [comment]
Some items such as pistons require complex recipe, so single chest clogs frequently and hard to manage, so pattern mode is not usable in those cases, this solves those problems by allowing separate items in other inventories.

**Comment by FakeDomi** [comment]
I see. I'll probably merge this on the weekend, but make it a config option.

**Comment by FakeDomi** [comment]
Sorry this took so long. I've refactored the code to my liking now, and made it a config option **that's off by default**. Check `eac.properties` in `./config`.
As a side note, I dislike how the transfer api inserts into the first available slot. Crafting droppers try to merge products with existing stacks first before filling empty slots, but this behavior is not supported in the api. Guess I'll keep using `Inventory` for now, and wait to see how many people adopt the new `Storage` interface without providing an `Inventory`.

**Pull request merged**
